### PR TITLE
Fixed some bugs and added support for title and data

### PR DESCRIPTION
**Pull request by tbleckert**
In the JS only version you couldn't specify a title when navigating and the start method didn't work properly. I also added strict mode and ran it through JSHint and fixed the warnings/errors from that. I also updated the Router.coffee with the new updates.

Great work with the router, it has everything I need.

### CODE REVIEW

**Comment by haithembelhaj** [comment]
WOW!! How did I miss this Merge request??!! 
Sorry I forgot about this project a long time ago.
So I took the time to update the whole thing in es6 and add some tests.

Can you explain a use case where the title is helpful?

**Comment by tbleckert** [comment]
Hehe it's never too late :D

About the title, you had it in the Router.coffee but under the name "name". In the JS version (Router.js) you just passed `null` to `History.replaceState` (and pushState). So I just fixed so the two versions matched. The `title` attribute is useful because it changes the browser window title. Usually a new page means a new title.

Just checked out the new version, great work!

**Comment by haithembelhaj** [comment]
Thanks! 
I added the title at the end of `navigate(url, trigger = true, replace = false, title = null)`. So I don't break existing code. 

Hope this helps

**Comment by tbleckert** [comment]
Great!

**Pull request closed without merging**
