### PR TITLE
Some bug fixes, also append_slash, before and after triggers improvement

### PR DESCRIPTION
**Pull request by fynjah**

### CODE REVIEW

**Comment by bzin** [comment]
This pull request is interesting. 
Is there any reason why you stop updating the code @haithembelhaj ?
I was actually to do a similar to correct the History.pushState.

Hope you can have time for an update :)

**Comment by fynjah** [comment]
@bzin btw, i have more fixes. Will see, may be in few days i will send updated pull request

**Comment by haithembelhaj** [comment]
First of all thank you for your work. This project was so outdated and I have to say that I nearly forgot about it. I took the time to update the whole thing to es6 and add some tests. 

I don't exactly get this merge request. 

Can you please explain to me what you are trying to accomplish here?

**Comment by fynjah** [comment]
@haithembelhaj Hi.. 
I'm using RouterJs in my project, and i've been experiencing problems with slashes in URL. So, I've added parametre "append_slash" which determins what to do with the slash in the end(trigger or not to trigger callback). You must provide true/false on route register.

Also i've been needed to trigger some functionality before and after Router's callback. For example - clean some DOM Objects everytime.

I have another changes - you may see it in my branch

I hope I was clear:)

**Comment by haithembelhaj** [comment]
@fynjah In which scenario do you become a slash at the end of a route?

**Comment by fynjah** [comment]
Did not clearly understand what you mean :\

If I understand you clear, than actually i don't remember the case when it happened:(

Now i'm using RouterJS like this:

```
 app = app || {};
 app.router = new Router({}, true); //this `true` is append_slash
 app.router.after = function() {
     var breadcrumb = $('.breadcrumb').html('');
     breadcrumb.append($('<li><a href="#/dashboard"><i class="fa fafw fa-home"></i> Home</a></li>'))
}


app.router.route('/packages/:pckg', function(pckg) {
     var $deferred = $.ajax({
         type: "GET",
         url: '/core/packages/' + pckg,
         dataType: 'html',
         cache: true,
         success: function(data) {
              $('#content').html(data);
         }
    });
    return $deferred; // returns $deferred object, so 'after' will be triggered on after $deferred will be resolved
});

app.router.start()
```

**Comment by haithembelhaj** [comment]
I just pushed a new version with 'optional url part support' so you could do something like this.

```
router.route('/packages(/:id)', fn) // will trigger for /packages and /packages/ID
```

Hope this helps

**Comment by haithembelhaj** [comment]
As of the `router.after` thingy I would prefer not to integrate such custom functionality in this really slim-router. And you could do it really easily with the actual version just like this

```
var app = app || {};

app.router = new Router(); 

app.afterRoute = function() {

     .....
}

app.router.route('/packages/:pckg', function(pckg) {

   return $.ajax({...}).complete(app.afterRoute);
});

app.router.start()
```

or if you really need it in more than one place

```
var app = app || {};

app.router = new Router(); 

app.afterRoute = function() {

     .....
}

// callAfter is where the whole magic happens
app.router.route('/packages/:pckg', callAfter(function(pckg) {

   return $.ajax({...})
}));

app.router.start()

// this function return an augmented version of fn that calls app.afterRoute 
function callAfter(fn){

  return function(){

    fn.apply(this, arguments).complete(app.afterRoute);
  }
}
```

**Comment by fynjah** [comment]
Got it) Thanks

**Pull request closed without merging**
